server:
  port: 5080

spring:
  application:
    name: attachments
  datasource:
    username: 'postgres'
    password: 'skylite=2011'
    url: jdbc:postgresql://localhost:5432/docs_db
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: true
    hibernate:
      ddl-auto: update